{application,identd,
             [{description,"A simple identd that simply returns random hexadecimals as the ident"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{identd_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[identd_app,identd_fsm,identd_listener,identd_sup]},
              {contributors,[]},
              {licenses,[ISC]},
              {links,[]}]}.
